// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(BarContext))]
    [Migration("20210616162856_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.LetnjiBar", b =>
                {
                    b.Property<int>("IDBara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("IDBara");

                    b.ToTable("LetnjiBar");
                });

            modelBuilder.Entity("Backend.Models.Lezaljka", b =>
                {
                    b.Property<int>("BrojLezaljke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BrojLezaljke")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarIDBara")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Tip");

                    b.HasKey("BrojLezaljke");

                    b.HasIndex("BarIDBara");

                    b.ToTable("Lezaljka");
                });

            modelBuilder.Entity("Backend.Models.Porudzbina", b =>
                {
                    b.Property<int>("IDPorudzbine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarIDBara")
                        .HasColumnType("int");

                    b.Property<string>("Hrana")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Hrana");

                    b.Property<string>("Pice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pice");

                    b.HasKey("IDPorudzbine");

                    b.HasIndex("BarIDBara");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("Backend.Models.Lezaljka", b =>
                {
                    b.HasOne("Backend.Models.LetnjiBar", "Bar")
                        .WithMany("Lezaljke")
                        .HasForeignKey("BarIDBara");

                    b.Navigation("Bar");
                });

            modelBuilder.Entity("Backend.Models.Porudzbina", b =>
                {
                    b.HasOne("Backend.Models.LetnjiBar", "Bar")
                        .WithMany("Porudzbine")
                        .HasForeignKey("BarIDBara");

                    b.Navigation("Bar");
                });

            modelBuilder.Entity("Backend.Models.LetnjiBar", b =>
                {
                    b.Navigation("Lezaljke");

                    b.Navigation("Porudzbine");
                });
#pragma warning restore 612, 618
        }
    }
}
